### PR TITLE
[GH-1310] Test that restoring an Elasticsearch snapshot works well enough to support Clio.

### PR DESCRIPTION
**Pull request by tbl3rd**
### Description

https://broadinstitute.atlassian.net/browse/GH-1310

Add a Bash script and some Helm YAML to maybe test an Elasticsearch snapshot restore for Clio.

Run `./elasticsearch-restore/test-restore.sh` for more information.

_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any JIRA issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: Ensure that you have added or updated tests
- [ ] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Comment by tbl3rd** [comment]
I expect people to have issues running this.
Please just report them so they can be addressed.
Thanks.

**Comment by aednichols** [comment]
I ran `sbt assembly` to get the JARs, then
```
./elasticsearch-restore/test-restore.sh dev
  /Users/anichols/Projects/clio/clio-server/target/scala-2.12/clio-server-b418519c54375431a07c29b1bb351d584395c5c2.jar
  /Users/anichols/Projects/clio/clio-client/target/scala-2.12/clio-client-b418519c54375431a07c29b1bb351d584395c5c2.jar
```
which had nominal output until it hit
```
Error: INSTALLATION FAILED: roles.rbac.authorization.k8s.io is forbidden: User "anichols@broadinstitute.org" cannot create resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "elasticsearch-restore-test-dev": requires one of ["container.roles.create"] permission(s).
helm.go:84: [debug] roles.rbac.authorization.k8s.io is forbidden: User "anichols@broadinstitute.org" cannot create resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "elasticsearch-restore-test-dev": requires one of ["container.roles.create"] permission(s).
INSTALLATION FAILED
```
which looks 100% like a lack of permissions on my account rather than an issue with the script.

It seems unlikely that I have permission to fix these permissions myself; how should we proceed?

**Comment by tbl3rd** [comment]
I agree, and I don't know.
Maybe you are not authorized for our `apiGroup`?
We need to get you `container.roles.create` in `rbac.authorization.k8s.io`.
Which command provoked that `Error`?

**Comment by aednichols** [comment]
The command was my stab at what you suggested, with self-built JARs.

```
./elasticsearch-restore/test-restore.sh dev
  /Users/anichols/Projects/clio/clio-server/target/scala-2.12/clio-server-b418519c54375431a07c29b1bb351d584395c5c2.jar
  /Users/anichols/Projects/clio/clio-client/target/scala-2.12/clio-client-b418519c54375431a07c29b1bb351d584395c5c2.jar
```

**Comment by aednichols** [comment]
Ooh, I accidentally re-ran the command above with my `anichols@firecloud.org` set as the active auth and it exited `0`.

I'm not sure whether it's a good idea to keep using my Terra super-user account like this though...

**Comment by tbl3rd** [comment]
Interesting. It still would be interesting to know the command it fails on.
Then we can ask in the usual Slack channel for an appropriate fix.

**Comment by aednichols** [comment]
> Interesting. It still would be interesting to know the command it fails on.

That was [this](https://github.com/broadinstitute/clio/pull/345#issuecomment-1128069604) with my `anichols@broadinstitute.org` account specified in `gcloud`.

**Review by aednichols — APPROVED** [review]

**Pull request merged**
