### PR TITLE
Added elasticsearch client and test. DSDEGP-1231

### PR DESCRIPTION
**Pull request by kshakir**
### Description

Elasticsearch status wired into the /health endpoint.
Config values, including the elasticsearch hosts, may be specified via environment variables.
Using elastic4s-http for the elasticsearch client.
Using testcontainers-scala for the elasticsearch client tests.
Step towards the nightly tests against a dev elasticsearch for DSDEGP-1231. A following PR will contain the python code to exercise these endpoints.
Includes workaround for docker-java issue related to reading macOS configs.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: Ensure that you have added or updated tests
- [x] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Review by tbl3rd — APPROVED** [review]
sbt assembly and test failed looking for a running docker image, which I also couldn't build because of the same exception, but I assume I'm just doing something wrong.

**Comment by kshakir** [comment]
@tbl3rd Grab the latest and give it another shot please? I traced down a workaround that fixes the problem for now.

**Comment by tbl3rd** [comment]
That looks good.
+    sys.props += "DOCKER_CONFIG" -> "/dev/null/workaround/docker-java/issues/806"
looks bizarre.  Does this just cleverly "break" DOCKER_CONFIG so it gets a default?

**Comment by kshakir** [comment]
Yep. See: https://github.com/docker-java/docker-java/blob/f43f174f64e88cdffa7259e3075671681f57c1fa/src/main/java/com/github/dockerjava/core/AuthConfigFile.java#L104-L159
1. If the config file doesn't exist, `AuthConfigFile.loadConfig` just returns an empty config.
2. Otherwise, it tries to parse the file using a Jackson mapping. In the case of issue 806, this is where Jackson fails because of an "unexpected" json element.
3. But `AuthConfigFile.loadConfig` assumes any exceptions are due to the wrong file type, eventually then trying to parse the config file with a really old `name=value` parser.

The "workaround" is to just change where the config file is being searched. As the config doesn't exist, option 1. above is triggered and the docker pull runs just fine.

**Comment by tbl3rd** [comment]
... and type-safe AF. ;-0

**Comment by kshakir** [comment]
Heh, I'm so used to reading scala now, that I forget that `… += … -> …` may not mean anything to most folks.

Squashing and merging unless there are other comments.

**Pull request merged**
