### PR TITLE
PO-10151 Patch in hyphen case for Clio command names.

### PR DESCRIPTION
**Pull request by danxmoran**
### Description

Clio in dev uses hypen-case for its command names, and that's what Trevyn built Zamboni against. Prod clio is so far behind that it's still using PascalCase for commands. This patches the prod client to use hyphen-case so we don't have to flip-flop zamboni.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: Ensure that you have added or updated tests
- [ ] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Comment by danxmoran** [comment]
New help statement for prod with this PR:
image

**Review by gbggrant — APPROVED** [review]
👍

**Comment by pshapiro4broad** [comment]
Maybe we should back out clio in prod until we release the latest in prod?

**Comment by danxmoran** [comment]
@pshapiro4broad I think we might have to, I'm pretty sure there's a bunch of auth work in dev that's not in prod which will be the next breakage with this change. That or we backport adding --research-project-id and just release the dev client into prod to get things working on the zamboni side.

**Comment by danxmoran** [comment]
Closing bc doomed to fail

**Pull request closed without merging**
