### PR TITLE
DSDEGP-2469 Move dont copy idats

### PR DESCRIPTION
**Pull request by tlangs**
### Description

Ops wants to move instead of copy Idats when delivering arrays.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: Ensure that you have added or updated tests
- [ ] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Review by pshapiro4broad — CHANGES_REQUESTED** [review]
I though we can't do this because idats can be shared between different arrays datasets. So we can never move, only copy.

**Comment by tlangs** [comment]
@gbggrant Is what @pshapiro4broad said true? If so, I'll close out the ops ticket as a won't do.

**Comment by pshapiro4broad** [comment]
> @gbggrant Is what @pshapiro4broad said true? If so, I'll close out the ops ticket as a won't do.

Didn't know there was a ticket for this; including the JIRA ticket the PR would be helpful.

**Comment by tlangs** [comment]
I don't understand how github names its PRs. Sometimes it includes the ticket from the branch name, sometimes it doesn't...

**Comment by tlangs** [comment]
Jira ticket is now in the PR name. DSDEGP-2469 to be specific.

**Comment by gbggrant** [comment]
We need to leave the idats in place so that reanalyses can be run.

**Pull request closed without merging**
