### PR TITLE
bogus change to make test fail

### PR DESCRIPTION
**Pull request by pshapiro4broad**
### Description

Just testing out github PR support in jenkins
----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: Ensure that you have added or updated tests
- [ ] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Comment by broadinst** [comment]
Can one of the admins verify this patch?

**Comment by pshapiro4broad** [comment]
add to whitelist

**Comment by broadinst** [comment]
Can one of the admins verify this patch?

**Comment by pshapiro4broad** [comment]
add to whitelist

**Comment by pshapiro4broad** [comment]
retest this please

**Comment by pshapiro4broad** [comment]
restest this please

**Comment by pshapiro4broad** [comment]
retest this please

**Comment by broadinst** [comment]
Can one of the admins verify this patch?

**Comment by pshapiro4broad** [comment]
add to whitelist

**Comment by pshapiro4broad** [comment]
retest this please

**Pull request closed without merging**
