### PR TITLE
DSDEGP-1406 Make audit directives return errors on failure.

### PR DESCRIPTION
**Pull request by danxmoran**
### Description

Before these changes, if our auditing logging raised an error it'd just be ignored.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: Ensure that you have added or updated tests
- [ ] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Comment by broadinst** [comment]
Can one of the admins verify this patch?

**Comment by pshapiro4broad** [comment]
test this please

**Comment by pshapiro4broad** [comment]
This looks 👍 but to me it raises more questions about failures while auditing.

Both error reporting and auditing currently use the same subsystem (logging). If auditing fails, will  error logging work? Should we use a different error reporting system (such as email, web service, etc) instead?

It seems like we'd need to carefully preserve the 'dropped' audit message at time of failure. E.g. if the message is 'resource X was moved from Y to Z' and it couldn't be audited, how would we get that information back? Or is it OK to lose that information?

**Comment by danxmoran** [comment]
I opened [DSDEGP-1417](https://broadinstitute.atlassian.net/browse/DSDEGP-1417) to track what we should do for error reporting when auditing fails.

**Pull request merged**
