### PR TITLE
POD-837 Added insert_size_metrics_path to BAM index

### PR DESCRIPTION
**Pull request by tlangs**
### Description

Adding `insert_size_metrics_path` to the Clio BAM index.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: Ensure that you have added or updated tests
- [ ] **Submitter**: If you're adding/switching libraries or otherwise changing the design, update the [design documentation](https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?pageId=114531509).
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
* Review cycle:
  * Team may comment on PR at will
  * **Reviewer assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to reviewer** for further feedback
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Move the JIRA issue to QA once this checklist is completed

### CODE REVIEW

**Review by gordonwade — APPROVED** [review]

**Review by tbl3rd — APPROVED** [review]
Do we want to support move-bam or deliver-bam?

**Comment by tlangs** [comment]
We already do.

**Comment by pshapiro4broad** [comment]
> > Do we want to support move-bam or deliver-bam?

> We already do.

@tlangs I don't see what you're referring to. This change adds a new URI field but makes no change to `BamDeliverer` or `pathsToDelete`. So it looks like this field isn't yet supported by deliver, move, delete or undeliver.

**Comment by tbl3rd** [comment]
> So it looks like this field isn't yet supported by deliver, move, delete or undeliver.

Thanks. That was my point.

**Comment by tlangs** [comment]
@pshapiro4broad BAMs in Clio closely mirror the CRAM implementation. For deletion, we don't delete CRAM metrics files, only sequence data. So, we will also not delete BAM metrics files. As for moving, there is no operational requirement to move the `insert_size_metrics_file`. This metrics file is being added solely to get BAM support in EDDy, and all other uses of the BAM index don't care about the metrics file.

**Comment by pshapiro4broad** [comment]
> @pshapiro4broad BAMs in Clio closely mirror the CRAM implementation. For deletion, we don't delete CRAM metrics files, only sequence data. So, we will also not delete BAM metrics files. As for moving, there is no operational requirement to move the insert_size_metrics_file. This metrics file is being added solely to get BAM support in EDDy, and all other uses of the BAM index don't care about the metrics file.

Ok, that's good to know. This is different from metrics files on other objects, such as Crams, where (I believe) we do something with every URI in the metadata. It may be worth adding a comment to the code to make this clear for a future maintainer.

On the other hand, if there's code in EDDy that's specific to a field in clio, maybe that's something that should be done in a clio-client command so EDDy doesn't need to be updated when a field in clio changes.

**Pull request merged**
